title:        pmcjury
tagline:      'Patrick McJury'
description:  ''
url:          http://pmcjury.com
version:      1.1.1
author:
  name:       'Patrick McJury'
  email:      'pmcjury@yahoo.com'
github:		  'https://github.com/pmcjury'
linkedin:     'http://www.linkedin.com/in/pmcjury'
twitter:      'https://twitter.com/pmcjury'
markdown:     redcarpet
permalink:    pretty
pygments:     true
paginate:     5
timezone:     'America/New_York'
exclude:      ['Gemfile', 'Gemfile.lock', 'README.md', 'CNAME', 'bin']